### ISSUE TITLE
ddraw.dll can't be loaded

### ISSUE THREAD

**Issue by sourcerunner** [CnCNet/ts-ddraw#13]
I'm using Win10 and having trouble with black screen and no menu problems. So I put the ddraw.dll into the game directory, but the problems retains, and I don't see the FPS, either. I have tried some other ddraw.dll, and they also can't work. Maybe the DLL isn't loaded at all? Why does this happen?

I'm using the lateset win10 and the game version is 1.006. Thanks!!

**Comment by sourcerunner** [comment]
Thanks for your reply! I have solved the problem!

The real problem for me is that I have the `ddraw.dll` in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs` in my registry, so the program can't use the patched version. Deleting this entry, the problems are gone.

Thanks again for your wonderful job!

**Comment by FunkyFr3sh** [comment]
@sourcerunner are you from china? Do you have 360 anti-virus?
