### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by daninthemix** [CnCNet/ts-ddraw#14]
How do you configure this? cnc-ddraw has an ini file, but this doesn't seem to. I want borderless fullscreen, I don't want my desktop res being changed.

**Comment by FunkyFr3sh** [comment]
Theres a settings file, but not currently included in the latest release. You could try the one from a older release:
https://github.com/CnCNet/ts-ddraw/releases/download/1.1.4.8/ddraw.ini

However, scaling isn't really supported too well, it's very experimental and wasn't updated for some time. I think it only works with the GDI renderer.

**Comment by daninthemix** [comment]
Closing  this as it was before I learned that cnc-ddraw works perfectly :)
