### ISSUE TITLE
problems about the resolution

### ISSUE THREAD

**Issue by lovelinability** [CnCNet/ts-ddraw#4]
Thank you very much for your great efforts! For that I can play RA2 on my WIN10 PC. But I have met with some problems, that is I can only choose the 1280x720 RESOLUTION, but I CANNOT choose another one, the bug is that when i choose one such as 1600x900, the right-side toolbar(in charge of building & manufacturing) disappears, along with that there are also a lot of display chaos. Really hope you can settle this bug!

**Comment by FunkyFr3sh** [comment]
Probably caused by dpi scaling, try to disable it for the game executable.

https://www.google.com/search?q=disable+high+dpi+scaling&num=30&source=lnms&tbm=isch&sa=X
